### PR TITLE
ui. add onsubmit.prevent event

### PR DESCRIPTION
**Pull request by federicoballarini**
Add v-on:submit.prevent event on forms.
Refer to https://github.com/NethServer/dev/issues/5966

### CODE REVIEW

**Comment by federicoballarini** [comment]
@edospadoni It works on `Virtual Hosts`, but not `Reverse Proxy`. Could you check when you are free?
Probably I'm missing something...

**Review by edospadoni — APPROVED** [review]

**Comment by edospadoni** [comment]
> @edospadoni It works on `Virtual Hosts`, but not `Reverse Proxy`. Could you check when you are free?
> Probably I'm missing something...

I've no idea :smile:. Have you checked that HTML structure is valid? missing closing tags, missing quote etc...

When the modal in open a warning is shown on terminal. Move the `advanced: false` declaration from line `314` to line `332` inside the `obj` variable.

**Comment by federicoballarini** [comment]
No, it doesn't work and it seems all ok. But I found a workaround: use `v-on:keyup.enter` event. It works. I commit it. If it is ok for you we can merge it. Cleaning cache, I have only one error related to tranalations, but seems everything ok.

**Comment by edospadoni** [comment]
> No, it doesn't work and it seems all ok. But I found a workaround: use `v-on:keyup.enter` event. It works. I commit it. If it is ok for you we can merge it. Cleaning cache, I have only one error related to tranalations, but seems everything ok.

Ok, but the problem of `advanced` prop is not related to cache. Please follow the instructions above and move it under `obj` variable.

The `v-on:keyup.enter` it's ok :+1:

**Pull request merged**
