### PR TITLE
Fix validation of websocket path

### PR DESCRIPTION
**Pull request by stephdl**

### CODE REVIEW

**Review by DavidePrincipi — COMMENTED** [review]
:thinking: I don't get why we are asking the user to digit a leading slash "/"... Isn't the underlying code already prepending it as needed?

**Comment by stephdl** [comment]
in fact it is a path that the user could fill if it cannot be found automatically, so in my mind it starts by a `/` but we could remove it, 

Do you prefer we remove this validation @DavidePrincipi  ?

**Comment by DavidePrincipi** [comment]
Someone wouldn't type it and someone else would expect it is required... The UI should help to achieve the goal: we'd accept both cases IMO: with and without the leading slash. 

There are many ways to achieve it, for instance a VueJS code that trims "/" and in the API we can assume the "/" is not allowed.

**Review by DavidePrincipi — CHANGES_REQUESTED** [review]
Please consider an alternative implementation that does not alter the current API and template code. 

As you'd like typing a leading slash, just add some JS code that trims it before sending it to the API.

It is the UI purpose: help the users to achieve their goals.

**Comment by stephdl** [comment]
obsoleted by https://github.com/NethServer/nethserver-httpd/pull/84

**Pull request closed without merging**
