### PR TITLE
Delegate the httpd log

### PR DESCRIPTION
**Pull request by stephdl**
Add the missing sudo Cmnd_alias to delegate log

### CODE REVIEW

**Comment by gsanchietti** [comment]
With such sudo configuration, the user will be able to access all system logs and not only the httpd ones.

For me, this is not the correct implementation but we can probably accept such limitation.

What do you think @DavidePrincipi and @filippocarletti ?

**Comment by stephdl** [comment]
@andre8244 moved the sudo false to sudo true, we still verify if  the application is delegated to the user, now the question is does the user with this API could read all logs in a terminal, if yes the LOG menu should not be visible if the user cannot be delegated

**Comment by gsanchietti** [comment]
A user with sudo access to system-log API can virtually read *any* file in the system.

**Comment by DavidePrincipi** [comment]
> With such sudo configuration, the user will be able to access all system logs and not only the httpd ones.

It's ok if the user is admin or member of the admins group. Instead of allowing the execution of `system-logs/execute` here, I'd go by adding it to the default helpers set for `domain admins`.

**Comment by stephdl** [comment]
lets close then

**Comment by stephdl** [comment]
lets close then

**Pull request closed without merging**
