### PR TITLE
ui & api. add DateTimezone and ShortOpenTag settings

### PR DESCRIPTION
**Pull request by federicoballarini**
Added DateTimezone and ShortOpenTag values into Settings page.
Refer to https://github.com/NethServer/dev/issues/5991

### CODE REVIEW

**Comment by federicoballarini** [comment]
The result should be like this:

Schermata 2019-12-15 alle 01 02 46

Waiting for review.
Sorry for 2 fix language commits: it's time to go to bed ^-^

**Review by stephdl — COMMENTED** [review]
nice work, works as expected, the php settings are updated to configuration database, so far no errors in logs

do we need the same for each Vhost, indeed if `PhpCustomSettings=enabled` we customize each vhost with `php_admin_value`, for example : 

```
      php_admin_value memory_limit 284M
      php_admin_value upload_max_filesize 4M
      php_admin_value post_max_size 8M
      php_admin_value max_execution_time 0
      php_admin_value max_input_time 0
      php_admin_value max_file_uploads 20
```

Screenshot_2019-12-15 System - ns7loc13 nethservertest org

**Comment by federicoballarini** [comment]
Ok @stephdl, I proceed with adding a commit to show these settings also on VHost page.

**Comment by stephdl** [comment]
nice, wait maybe the approval of others, we could add it later

**Comment by federicoballarini** [comment]
> nice, wait maybe the approval of others, we could add it later

I committed now for Virtual Host settings. We can revert them if are not ok.

**Review by stephdl — CHANGES_REQUESTED** [review]
you missed to modify the values inside the vhost template

when the php is set to default, then you have to modify there

https://github.com/NethServer/nethserver-httpd/blob/master/virtualhosts/etc/e-smith/templates/httpd/vhost-extra/30directory21RhPhpAdminValues

When the php is set to another values, you modify the php values inside each php-fpm pool

https://github.com/NethServer/nethserver-httpd/blob/master/virtualhosts/etc/e-smith/templates/etc/opt/rh/rh-php71/php-fpm.d/000-virtualhost.conf/10Base

https://github.com/NethServer/nethserver-httpd/blob/master/virtualhosts/etc/e-smith/templates/etc/opt/rh/rh-php72/php-fpm.d/000-virtualhost.conf/10Base

something more it could be nice to rebase your translation commit in one piece, `git rebase -i ` can help you, ping us if you want tips (I still learn after git each day)

**Comment by federicoballarini** [comment]
Maybe squash and merge by dev team is better. I can do disaster :)

**Comment by stephdl** [comment]
> Maybe squash and merge by dev team is better. I can do disaster :)

`git check-out -b myTestBranch`
then you are on another test branch, you can do your disaster

`git rebase -i HEAD~7`
the commit you want to fix, is 1be1d8d22f13575e55d2cbe87b4afaff0e5014d9, change `pick` by `f`, then save and exit

the squash and merge will steal you some commits in GH timeline, it is not fair

**Comment by stephdl** [comment]
you have made a typo it is not `date_timezone` but `date.timezone` to pass the new value to php, I just tested it with a phpinfo

`php_admin_value[date.timezone] = Europe/Berlin`

else it work as expected

**Review by stephdl — CHANGES_REQUESTED** [review]
you have made a typo it is not `date_timezone` but `date.timezone` to pass the new value to php, I just tested it with a phpinfo

`php_admin_value[date.timezone] = Europe/Berlin`
or
`php_admin_value date.timezone`
else it works as expected

**Review by stephdl — APPROVED** [review]

**Comment by federicoballarini** [comment]
> you have made a typo it is not `date_timezone` but `date.timezone` to pass the new value to php, I just tested it with a phpinfo
> 
> `php_admin_value[date.timezone] = Europe/Berlin`
> or
> `php_admin_value date.timezone`
> else it works as expected

You are right @stephdl. Thank you so much for your help :)

**Review by DavidePrincipi — CHANGES_REQUESTED** [review]
Nice development work, but I'm afraid we're going a bit out of track!

Please see my comment on the related issue.

**Comment by federicoballarini** [comment]
> Nice development work, but I'm afraid we're going a bit out of track!
> 
> Please see my comment on the related issue.

Yes, I answer you there :)

**Comment by DavidePrincipi** [comment]
I'm really sorry to do it :cry: 

https://github.com/NethServer/dev/issues/5991#issuecomment-566462625

**Pull request closed without merging**
