### PR TITLE
Update 20ssl_engine

### PR DESCRIPTION
**Pull request by dasois**
It is general recommendation to set HSTS header for https

### CODE REVIEW

**Review by gsanchietti — CHANGES_REQUESTED** [review]
I'm not sure this is the right approach: the httpd server could host also HTTP applications.
If we enforce the HSTS such applications should always be accessed via HTTPS and this could cause many problems if the certificate is not valid.
Also, a sysadmin could have installed an application which doesn't work with SSL: we can't break existing installations!

If we want to support HSTS, it should be an option disabled by default.

See also: https://community.nethserver.org/t/template-etc-httpd-conf-d-ssl-conf/8778/15

**Comment by danb35** [comment]
A two-year HSTS header (with no way to configure this length of time) seems excessive, and is a change from (recent) previous Mozilla recommendations--they'd previously recommended (along with pretty much everyone else) one year.  The longer this time is, the longer you (and your users) are potentially locked out of your site if there's a TLS issue.  Do you have a link to any discussion about this change?

**Comment by dasois** [comment]
How about this:
We add a checkbox to the vhost page that activates the HSTS after showing a warning prompt that one should verify connection and certificate. We then set the header after confirmation to the recommended time by Mozilla.

Am 22. Juli 2019 12:45:30 MESZ schrieb danb35 <notifications@github.com>:
>A two-year HSTS header (with no way to configure this length of time)
>seems excessive, and is a change from (recent) previous Mozilla
>recommendations--they'd previously recommended (along with pretty much
>everyone else) one year.  The longer this time is, the longer you (and
>your users) are potentially locked out of your site if there's a TLS
>issue.  Do you have a link to any discussion about this change?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/NethServer/nethserver-httpd/pull/42#issuecomment-513740623

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by danb35** [comment]
> We then set the header after confirmation to the recommended time by Mozilla.

Again, I wouldn't agree with this without seeing some rationale for the change doubling that time.

**Comment by dasois** [comment]
I don't think there is a big difference setting it to one year or two, but i could be wrong.



Am 22. Juli 2019 14:09:16 MESZ schrieb danb35 <notifications@github.com>:
>> We then set the header after confirmation to the recommended time by
>Mozilla.
>
>Again, I wouldn't agree with this without seeing some rationale for the
>change doubling that time.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/NethServer/nethserver-httpd/pull/42#issuecomment-513764670

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by gsanchietti** [comment]
Please continue the discussion on community, then reopen the PR with the full implementation.

**Pull request closed without merging**
